version: '3.0'
services:
    nginx:
        #restart: always
        image: nginx:alpine
        ports:
            - 80:80
        volumes:
            - /home/semenov/MAptekaGet/ma-updater.conf:/etc/nginx/conf.d/default.conf
            - /www
        depends_on:
            - mapteka-get
        command: /bin/ash -c "chmod 777 /www && nginx -g 'daemon off;'"
    
    mapteka-get:
        #restart: always
        build:
            context: .
        ports:
            - 8083:80
        environment:
            - UPD_BASE_URI=http://nginx/
            - EXT_UPD_URI=http://test-mapteka-updater.itapteka.loc/
            - ESC_CONVERT_URI=http://w7-grishin:1972/csp/updaptservice/User.UpdAptToEscService.cls
            - ESC_URI_PREFIX=http://test-mapteka-updater.itapteka.loc/api/v1/esc/

