version: '3.0'
services:
    nginx:
        #restart: always
        image: nginx:alpine
        ports:
            - 80:80
        volumes:
            - /var/opt/etc/ma-updater.conf:/etc/nginx/conf.d/ma-updater.conf
            - /www/mapteka-updater:/usr/share/nginx/www
        depends_on:
            - mapteka-get
        command: /bin/ash -c "rm /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    
    mapteka-get:
        #restart: always
        build:
            context: .
        ports:
            - 8083:80
        environment:
            - UPD_BASE_URI=http://nginx/storage/upd/
            - ESC_CONVERT_URI=http://w7-grishin:1972/csp/updaptservice/User.UpdAptToEscService.cls
            - ESC_URI_PREFIX=http://test-mapteka-updater.itapteka.loc/api/v1/esc/

