version: '3.0'
services:
    nginx:
        #restart: always
        image: nginx:alpine
        ports:
            - 80:80
        volumes:
            - /var/opt/etc/nginx.conf:/etc/nginx/conf.d/ma-updater.conf.template
        depends_on:
            - mapteka-get
        command: /bin/bash -c "envsubst < /etc/nginx/conf.d/ma-updater.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    
    mapteka-get:
        #restart: always
        build:
            context: .
        ports:
            - 8083:8080
        environment:
            - UPD_BASE_URI=http://nginx/storage/upd/
            - ESC_CONVERT_URI=http://w7-grishin:1972/csp/updaptservice/User.UpdAptToEscService.cls
            - ESC_URI_PREFIX=http://nginx/storage/esc/

