version: '3.0'
services:
    nginx:
        #restart: always
        image: nginx:alpine
        ports:
            - 80:80
        volumes:
            - /home/semenov/MAptekaGet/ma-updater.conf:/etc/nginx/conf.d/default.conf
            - /www
        depends_on:
            - mapteka-get
        command: /bin/ash -c "chmod 777 /www && nginx -g 'daemon off;'"
    
    mapteka-get:
        #restart: always
        build:
            context: .
        ports:
            - 8083:80
        depends_on:
            - postgres
        environment:
            - STATIC_BASE_URI=http://nginx/
            - ESC_CONVERT_URI=http://w7-grishin:1972/csp/updaptservice/User.UpdAptToEscService.cls
            - ESC_EXT_SCHEME=http
            - DB_CONNECTION_STR=server=postgres;port=5432;database=mapteka_get;user id=mapteka_get"
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres

    postgres:
        # restart: always
        image: postgres:alpine
        ports:
            - 5432:5432


